### ISSUE TITLE
Function not Implement

### ISSUE THREAD

**Issue by Xen0sWang** [zeth/inputs#114]
When i use the logitech f710 gamepad and try to set_vibration,the error raise,how can i fix it?

**Comment by zeth** [comment]
Can you give the whole traceback please?

**Comment by clausMeko** [comment]
I am no python expert, but I guess thats the issue:

```python
stack: Traceback (most recent call last):
  File "/home/clausbissinger/go/src/github.com/MeKo-Tech/Emanetics/src/Emanetics/Emanetics/controls/gamepad.py", line 165, in vibrate
    self._pad.set_vibration(0.30, 0.30, 500)
  File "/home/clausbissinger/go/src/github.com/MeKo-Tech/Emanetics/venv/lib/python3.11/site-packages/inputs.py", line 2983, in set_vibration
    self._set_vibration_nix(left_motor, right_motor, duration)
  File "/home/clausbissinger/go/src/github.com/MeKo-Tech/Emanetics/venv/lib/python3.11/site-packages/inputs.py", line 2969, in _set_vibration_nix
    code = self.__get_vibration_code(left_motor, right_motor, duration)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clausbissinger/go/src/github.com/MeKo-Tech/Emanetics/venv/lib/python3.11/site-packages/inputs.py", line 2963, in __get_vibration_code
    buf_conts = ioctl(self._write_device, 1076905344, inner_event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 38] Function not implemented
```

It's from Ubuntu 22.04.1
