### ISSUE TITLE
MacBook Keyboard BadPrototypeError

### ISSUE THREAD

**Issue by kielnino** [zeth/inputs#12]
When I run the example Code

```python
inputs import get_key
while 1:
    events = get_key()
    for event in events:
        print(event.ev_type, event.code, event.state)
```
on my MacBook Pro Late 2011 with maxOs 10.12.3 I get the following error:

```
Process Process-1:
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "//anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "//anaconda/lib/python2.7/site-packages/inputs.py", line 1913, in mac_keyboard_process
    class MacKeyboardSetup(NSObject):
BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector init_with_handler of MacKeyboardSetup at 0x106bca308>
```
Both, `inputs` and `PyObjC` has been installed with `pip`

**Comment by WayneKeenan** [comment]
I have the same issue

**Comment by WayneKeenan** [comment]
Summary of results :

Both the native and home-brew versions of Python 2 and Python 3 error with: 
`objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector init_with_handler of MacKeyboardSetup at 0xXXXXXXXX`

Apart from the native Pytohn2, which suffers from a sub-process crash (stack trace included below)

Test code:

```
from inputs import get_key, devices

print(devices.keyboards)

while 1:
    events = get_key()
    for event in events:
        print(event.ev_type, event.code, event.state)

```

# Homebrew Python 2.7.1 + pyobj 3.2.1

```
/usr/local/bin/python test_input.py 
[inputs.Keyboard("/dev/input/by-id/usb-A_Nice_Keyboard-event-kbd")]
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wayne/local.projects/PiCraft/python/src/picraft/inputs.py", line 1915, in mac_keyboard_process
    class MacKeyboardSetup(NSObject):
BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector init_with_handler of MacKeyboardSetup at 0x110573d98>

```

# Homebrew Python 3.6.0 + pyobj 3.2.1

```
/usr/local/bin/python3 test_input.py 
[inputs.Keyboard("/dev/input/by-id/usb-A_Nice_Keyboard-event-kbd")]
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wayne/local.projects/PiCraft/python/src/picraft/inputs.py", line 1915, in mac_keyboard_process
    class MacKeyboardSetup(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector init_with_handler of MacKeyboardSetup at 0x108cf0ed0>
```


# 'native' Python 3.6.0 

```
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 test_input.py 
[inputs.Keyboard("/dev/input/by-id/usb-A_Nice_Keyboard-event-kbd")]
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wayne/local.projects/PiCraft/python/src/picraft/inputs.py", line 1915, in mac_keyboard_process
    class MacKeyboardSetup(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector init_with_handler of MacKeyboardSetup at 0x107968920>
```
'

# 'native Python 2.7.0 

/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 test_input.py 
[inputs.Keyboard("/dev/input/by-id/usb-A_Nice_Keyboard-event-kbd")]

_sub-process crash, stack trace:_

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdispatch.dylib             	0x00007fffb1e96a3f _dispatch_assert_queue_fail + 99
1   libdispatch.dylib             	0x00007fffb1e8f150 dispatch_assert_queue + 155
2   com.apple.AppKit              	0x00007fff9a54df77 -[NSPersistentUIRestorer restoreStateFromRecords:usingDelegate:completionHandler:] + 192
3   com.apple.AppKit              	0x00007fff9aca15d9 -[NSPersistentUIManager restoreAllPersistentStateWithCompletionHandler:] + 272
4   com.apple.AppKit              	0x00007fff9a258e62 -[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:completionHandler:] + 368
5   com.apple.AppKit              	0x00007fff9a258bdc -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 539
6   com.apple.AppKit              	0x00007fff9a25883b -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 661
7   com.apple.Foundation          	0x00007fff9e198e1d -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290
8   com.apple.Foundation          	0x00007fff9e198c97 _NSAppleEventManagerGenericHandler + 102
9   com.apple.AE                  	0x00007fff9d59df26 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 544
10  com.apple.AE                  	0x00007fff9d59dc9d dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 39
11  com.apple.AE                  	0x00007fff9d59dba9 aeProcessAppleEvent + 312
12  com.apple.HIToolbox           	0x00007fff9bcc9ddf AEProcessAppleEvent + 55
13  com.apple.AppKit              	0x00007fff9a2540ed _DPSNextEvent + 1833
14  com.apple.AppKit              	0x00007fff9a9cf85e -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
15  com.apple.AppKit              	0x00007fff9a2487ab -[NSApplication run] + 926
16  libffi.dylib                  	0x00007fffb0f11f1c ffi_call_unix64 + 76
17  libffi.dylib                  	0x00007fffb0f127b1 ffi_call + 937
18  _objc.so                      	0x00000001011b43d7 PyObjCFFI_Caller + 2253
19  _objc.so                      	0x00000001011c7028 0x10119a000 + 184360
20  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
21  org.python.python             	0x0000000100be578b PyEval_EvalFrameEx + 11223
22  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
23  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
24  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
25  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
26  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
27  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
28  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
29  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
30  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
31  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
32  org.python.python             	0x0000000100b884d1 0x100b60000 + 165073
33  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
34  org.python.python             	0x0000000100b753ac 0x100b60000 + 86956
35  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
36  org.python.python             	0x0000000100bb1223 0x100b60000 + 332323
37  org.python.python             	0x0000000100baca78 0x100b60000 + 313976
38  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
39  org.python.python             	0x0000000100be578b PyEval_EvalFrameEx + 11223
40  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
41  org.python.python             	0x0000000100b884d1 0x100b60000 + 165073
42  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
43  org.python.python             	0x0000000100be5fe5 PyEval_EvalFrameEx + 13361
44  org.python.python             	0x0000000100be9475 0x100b60000 + 562293
45  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
46  org.python.python             	0x0000000100be9475 0x100b60000 + 562293
47  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
48  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
49  org.python.python             	0x0000000100b884d1 0x100b60000 + 165073
50  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
51  org.python.python             	0x0000000100b753ac 0x100b60000 + 86956
52  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
53  org.python.python             	0x0000000100bb1223 0x100b60000 + 332323
54  org.python.python             	0x0000000100baca78 0x100b60000 + 313976
55  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
56  org.python.python             	0x0000000100be578b PyEval_EvalFrameEx + 11223
57  org.python.python             	0x0000000100be9475 0x100b60000 + 562293
58  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
59  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
60  org.python.python             	0x0000000100b884d1 0x100b60000 + 165073
61  org.python.python             	0x0000000100b6a6fb PyObject_Call + 99
62  org.python.python             	0x0000000100b6a889 0x100b60000 + 43145
63  org.python.python             	0x0000000100b6a821 PyObject_CallFunction + 187
64  org.python.python             	0x0000000100b9ad9b _PyObject_GenericGetAttrWithDict + 251
65  org.python.python             	0x0000000100be4b02 PyEval_EvalFrameEx + 8014
66  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
67  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
68  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
69  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
70  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
71  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
72  org.python.python             	0x0000000100b7fb00 0x100b60000 + 129792
73  org.python.python             	0x0000000100be0196 0x100b60000 + 524694
74  org.python.python             	0x0000000100be64d4 PyEval_EvalFrameEx + 14624
75  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
76  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
77  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
78  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
79  org.python.python             	0x0000000100be93e2 0x100b60000 + 562146
80  org.python.python             	0x0000000100be5e4e PyEval_EvalFrameEx + 12954
81  org.python.python             	0x0000000100be29be PyEval_EvalCodeEx + 1617
82  org.python.python             	0x0000000100be2367 PyEval_EvalCode + 48
83  org.python.python             	0x0000000100c025dd 0x100b60000 + 665053
84  org.python.python             	0x0000000100c02680 PyRun_FileExFlags + 133
85  org.python.python             	0x0000000100c021d1 PyRun_SimpleFileExFlags + 702
86  org.python.python             	0x0000000100c13b6a Py_Main + 3094
87  libdyld.dylib                 	0x00007fffb1eba235 start + 1

```

**Comment by zeth** [comment]
Mac OS X made backwards incompatible changes in their apis, I am looking into this.
