### ISSUE TITLE
inputs  does not recognise a Joystick device,  UnpluggedError: No gamepad found.

### ISSUE THREAD

**Issue by nickums** [zeth/inputs#26]
My Joystick is  connected but only devices seen are Mouse and Keyboard, and get_game pad fails.
(Winows10 Python3.6)
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\inputs.py", line 2711, in get_gamepad
    gamepad = devices.gamepads[0]
IndexError: list index out of range
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Python/Dhruve and me/Pygame/device_inputs.py", line 22, in <module>
    events = get_gamepad()
  File "C:\Python\Python36\lib\site-packages\inputs.py", line 2713, in get_gamepad
    raise UnpluggedError("No gamepad found.")
inputs.UnpluggedError: No gamepad found.

**Comment by zeth** [comment]
Which Joystick is it? Is it possible to map it to an Xbox controller?
