### ISSUE TITLE
freeze_support ERROR (keyboard)

### ISSUE THREAD

**Issue by SmartySmart702** [zeth/inputs#48]
I have this error when I use the keyboard key print example script.
If I work with the Gamepad listener  everything works fine!
I'm new to programing so I dont' know what this means.

Win 10 x64

`An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

**Comment by zeth** [comment]
Interesting, I have never seen that before. I will have a look.

**Comment by SmartySmart702** [comment]
Here is the whole Console Log. Maybe it helps you.

`
C:\Users\WS-001\Desktop\Programming\Python\Robot>python InputTest.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\WS-001\Desktop\Programming\Python\Robot\InputTest.py", line 4, in <module>
    events = get_key()
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2940, in get_key
    return keyboard.read()
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2313, in read
    return next(iter(self))
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2273, in __iter__
    event = self._do_iter()
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2292, in _do_iter
    data = self._get_data(read_size)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2365, in _get_data
    return self._pipe.recv_bytes()
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2330, in _pipe
    self._listener.start()
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function InputDevice.__del__ at 0x000002CA36EECC80>
Traceback (most recent call last):
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\site-packages\inputs.py", line 2337, in __del__
  File "C:\Users\WS-001\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 124, in terminate
AttributeError: 'NoneType' object has no attribute 'terminate'
`


And here is the Code I'm running.

`import inputs
from inputs import get_key
while 1:
    events = get_key()
    for event in events:
        print(event.ev_type, event.code, event.state)
`

**Comment by SmartySmart702** [comment]
Anything new about this issue? I really like your library and it would be useful if I don't need an extra library for keyboard input :D

**Comment by cwlinghk** [comment]
I met the same issue

**Comment by singhjayant92** [comment]
This is expected on Windows. Just put it under
```
if __name__ == "__main__":
    while 1:
        events = get_key()
        if events:
            for event in events:
                print(event.ev_type, event.code, event.state)
```
